<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemSeeder extends Seeder
{
    public function run()
    {
        $items = [
            [1, 1, null, 'Soep Ling Fa', 3.8, 'SOEP', null],
            [2, 2, null, 'Kippensoep', 2.9, 'SOEP', ''],
            [3, 3, null, 'Tomatensoep', 2.9, 'SOEP', null],
            [4, 4, null, 'Haaienvinnensoep', 3.1, 'SOEP', null],
            [5, 5, null, 'Champignonsoep', 3.3, 'SOEP', null],
            [6, 6, null, 'Pekingsoep', 3.8, 'SOEP', null],
            [7, 7, null, 'Wan Tan Soep', 4.3, 'SOEP', null],
            [8, 8, null, 'Chinese Champignonsoep', 4.1, 'SOEP', null],
            [9, 10, null, 'Loempia Ling Fa', 6.2, 'VOORGERECHT', 'met atjar, ananas en pindasaus'],
            [10, 11, null, 'Loempia Compleet', 6.2, 'VOORGERECHT', 'met gesmoord rundvlees en pikante saus'],
            [11, 12, null, 'Loempia met Kip', 3.9, 'VOORGERECHT', null],
            [12, 13, null, 'Loempia', 3.8, 'VOORGERECHT', null],
            [13, 14, null, 'Chinese mini loempia', 4.9, 'VOORGERECHT', '4 st.'],
            [14, 14, 'A', 'Vegetarische mini loempia', 4.9, 'VOORGERECHT', '12 st.'],
            [15, 15, null, 'Kroepoek', 2.5, 'VOORGERECHT', null],
            [16, 15, 'A', 'Casave Kroepoek', 2.7, 'VOORGERECHT', null],
            [17, 16, null, 'Pangsit Goreng', 3.9, 'VOORGERECHT', '7 st.'],
            [18, 17, null, 'Pisang Goreng', 3.4, 'VOORGERECHT', '5 st.'],
            [19, 18, null, 'Chinese Dim Sum', 5.4, 'VOORGERECHT', 'mini loempia, kerry ko, pangsit goreng, garnalenpasteitje'],
            [20, 19, null, 'Saté Babi', 5.4, 'VOORGERECHT', '4 st.'],
            [21, 20, null, 'Saté Ajam', 5.4, 'VOORGERECHT', '4 st.'],
            [22, 20, 'A', 'Saté Garnalen', 9.9, 'VOORGERECHT', '3 st.'],
            [23, 21, null, 'Fong Mei Ha', 8.1, 'VOORGERECHT', 'krokant gepaneerd garnalen. 4 st.'],
            [24, 22, null, 'Patat', 2.3, 'VOORGERECHT', null],
            [25, 23, null, 'Tsa Siu Mai', 3.5, 'VOORGERECHT', 'gebakken vleespasteitje. 4 st.'],
            [26, 24, null, 'Atjar', 3, 'VOORGERECHT', null],
            [27, 25, null, 'Witte Rijst', 3, 'VOORGERECHT', null],
            [28, 26, null, 'Grote pindasaus', 3.9, 'VOORGERECHT', null],
            [29, 27, null, 'Kleine pindasaus', 2.3, 'VOORGERECHT', null],
            [30, 28, null, 'Kippenpootje', 2.3, 'VOORGERECHT', null],
            [31, 29, null, 'Halve kip', 6, 'VOORGERECHT', null],
            [32, 29, 'H', 'Kroket', 1.4, 'VOORGERECHT', null],
            [33, 29, 'G', 'Frikandel', 1.4, 'VOORGERECHT', null],
            [34, 180, 'H', 'Kleine Sambal', 2.5, 'VOORGERECHT', null],
            [35, 30, null, 'Bami of Nasi Goreng Ling Fa', 14.3, 'BAMI EN NASI GERECHTEN', 'Foe Yong Hai, Babi Pangang, saté en kippenpootje'],
            [36, 31, null, 'Bami of Nasi Goreng met ei', 5, 'BAMI EN NASI GERECHTEN', null],
            [37, 32, null, 'Bami of Nasi Goreng speciaal', 8.5, 'BAMI EN NASI GERECHTEN', null],
            [38, 33, null, 'Bami of Nasi Goreng met saté', 8.5, 'BAMI EN NASI GERECHTEN', '3 st.'],
            [39, 34, null, 'Nasi Yeung Chow', 10.9, 'BAMI EN NASI GERECHTEN', null],
            [40, 34, 'A', 'Nasi Yeung Chow', 13, 'BAMI EN NASI GERECHTEN', 'met garnaaltjes en Cha Sieuw-vlees'],
            [41, 35, null, 'Bami of Nasi Malay', 9.3, 'BAMI EN NASI GERECHTEN', null],
            [42, 36, null, 'Bami of Nasi met kipfilet', 9.3, 'BAMI EN NASI GERECHTEN', null],
            [43, 37, null, 'Bami of Nasi met varkensvlees', 9.3, 'BAMI EN NASI GERECHTEN', null],
            [44, 38, null, 'Bami of Nasi met garnalen', 14.3, 'BAMI EN NASI GERECHTEN', null],
            [45, 39, null, 'Bami of Nasi met ossenhaas', 15.3, 'BAMI EN NASI GERECHTEN', null],
            [46, 40, null, 'Babi Pangang, Foe Yong Hani en saté', 15.8, 'COMBINATIE GERECHTEN (met witte rijst)', null],
            [47, 41, null, 'Babi Pangang, Tjap Tjoy en saté', 15.8, 'COMBINATIE GERECHTEN (met witte rijst)', null],
            [48, 42, null, 'Babi Pangang, Koe Loe Yuk en saté', 15.8, 'COMBINATIE GERECHTEN (met witte rijst)', null],
            [49, 43, null, 'Babi Pangang, Tau Sie Kai en saté', 16.5, 'COMBINATIE GERECHTEN (met witte rijst)', null],
            [50, 44, null, 'Koe Loe Yuk, Foe Yong Hai en saté', 15.8, 'COMBINATIE GERECHTEN (met witte rijst)', null],
            [51, 45, null, 'Koe Loe Yuk, Tjap Tjoy en saté', 15.8, 'COMBINATIE GERECHTEN (met witte rijst)', null],
            [52, 46, null, 'Foe Yong Hai, Tjap Tjoy en saté', 15.8, 'COMBINATIE GERECHTEN (met witte rijst)', null],
            [53, 47, null, 'Foe Yong Hai, Kip Kerrie en Saté', 16.5, 'COMBINATIE GERECHTEN (met witte rijst)', null],
            [54, 50, null, 'Mihoen Ling Fa', 16.4, 'MIHOEN GERECHTEN', 'Foe Yong Hai, Babi Pangang, saté en kippenpootje'],
            [55, 51, null, 'Mihoen met varkensvlees', 9.3, 'MIHOEN GERECHTEN', null],
            [56, 52, null, 'Mihoen met kipfilet', 10.4, 'MIHOEN GERECHTEN', null],
            [57, 53, null, 'Mihoen met ossenhaas', 16.4, 'MIHOEN GERECHTEN', null],
            [58, 54, null, 'Mihoen met garnalen', 15.3, 'MIHOEN GERECHTEN', null],
            [59, 55, null, 'Mihoen Singapore-style', 11.9, 'MIHOEN GERECHTEN', 'met kleine garnaaltjes en Cha Sieuw-vlees en kerrie poeder'],
            [60, 56, null, 'Mihoen met Cha Sieuw vlees', 11.2, 'MIHOEN GERECHTEN', null],
            [61, 57, null, 'Chinese Bami Ling Fa', 16.9, 'CHINESE BAMI GERECHTEN', 'Foe Yong Hai, Babi Pangang, saté en kippenpootje'],
            [62, 58, null, 'Chinese Bami met varkensvlees', 10.1, 'CHINESE BAMI GERECHTEN', null],
            [63, 58, 'A', 'Chinese Bami met kipfilet', 11.2, 'CHINESE BAMI GERECHTEN', null],
            [64, 58, 'B', 'Chinese Bami met Cha Sieuw-vlees', 12.2, 'CHINESE BAMI GERECHTEN', null],
            [65, 58, 'C', 'Chinese Bami met garnalen', 15.8, 'CHINESE BAMI GERECHTEN', null],
            [66, 58, 'D', 'Chinese Bami met ossenhaas', 17.4, 'CHINESE BAMI GERECHTEN', null],
            [67, null, 'M1', 'Bami of Nasi Rames Ling Fa', 15.3, 'INDISCHE GERECHTEN', 'Babi Pangan, Foe Yong Hai, Daging Roedjak, Atjar en kippootje'],
            [68, null, 'M2', 'Bami of Nasi Rames', 8.8, 'INDISCHE GERECHTEN', null],
            [69, null, 'M3', 'Bami of Nasi Rames speciaal', 10.8, 'INDISCHE GERECHTEN', null],
            [70, null, 'M4', 'Gado Gado', 7.6, 'INDISCHE GERECHTEN', 'met witte rijst'],
            [71, null, 'M5', 'Daging Smoor', 13.3, 'INDISCHE GERECHTEN', 'met witte rijst'],
            [72, null, 'M6', 'Daging Roedjak', 13.3, 'INDISCHE GERECHTEN', 'met witte rijst'],
            [73, 59, null, 'Foe Yong Hai Ling Fa', 16.4, 'EIERGERECHTEN (met witte rijst)', 'ossenhaas, garnalen en kipfilet'],
            [74, 60, null, 'Foe Yong Hai met varkensvlees', 8.8, 'EIERGERECHTEN (met witte rijst)', null],
            [75, 61, null, 'Foe Yong Hai met kipfilet', 9.2, 'EIERGERECHTEN (met witte rijst)', null],
            [76, 62, null, 'Foe Yong Hai met garnalen', 15.3, 'EIERGERECHTEN (met witte rijst)', null],
            [77, 63, null, 'Foe Yong Hai met krab', 15.3, 'EIERGERECHTEN (met witte rijst)', null],
            [78, 63, 'A', 'Foe Yong Hai met Cha Sieuw Vlees', 11.2, 'EIERGERECHTEN (met witte rijst)', null],
            [79, 63, 'B', 'Foe Yong Hai met ossenhaas', 16.4, 'EIERGERECHTEN (met witte rijst)', null],
            [80, 64, null, 'Tjap Tjoy Ling Fa', 16.4, 'GROENTEN GERECHTEN (met witte rijst)', 'ossenhaas, garnalen en kipfilet'],
            [81, 65, null, 'Tjap Tjoy met varkensvlees', 8.8, 'GROENTEN GERECHTEN (met witte rijst)', null],
            [82, 66, null, 'Tjap Tjoy met kipfilet', 9.2, 'GROENTEN GERECHTEN (met witte rijst)', null],
            [83, 67, null, 'Tjap Tjoy met ossenhaas', 16.4, 'GROENTEN GERECHTEN (met witte rijst)', null],
            [84, 68, null, 'Tjap Tjoy met garnalen', 15.3, 'GROENTEN GERECHTEN (met witte rijst)', null],
            [85, 70, null, 'Babi Pangang', 12.2, 'VLEES GERECHTEN (met witte rijst)', null],
            [86, 71, null, 'Babi Pangang in ketjapsaus', 12.3, 'VLEES GERECHTEN (met witte rijst)', null],
            [87, 72, null, 'Cha Sieuw', 13.3, 'VLEES GERECHTEN (met witte rijst)', 'rood geroosterd varkensvlees'],
            [88, 73, null, 'Cha Sieuw in pikante saus', 13.8, 'VLEES GERECHTEN (met witte rijst)', null],
            [89, 74, null, 'Geroosterde speenvarken', 13.8, 'VLEES GERECHTEN (met witte rijst)', null],
            [90, 75, null, 'Koe Loe Yuk', 11.9, 'VLEES GERECHTEN (met witte rijst)', 'bolletjes vlees met zoetzure saus'],
            [91, 76, null, 'Varkenshaas met kerriesaus', 11.9, 'VLEES GERECHTEN (met witte rijst)', null],
            [92, 77, null, 'Varkenshaas met ketjapsaus', 11.9, 'VLEES GERECHTEN (met witte rijst)', null],
            [93, 78, null, 'Varkenshaas met tomatensaus', 11.9, 'VLEES GERECHTEN (met witte rijst)', null],
            [94, 78, 'A', 'Varkenshaas met champignons in knoflooksaus', 11.9, 'VLEES GERECHTEN (met witte rijst)', null],
            [95, 78, 'B', 'Varkenshaas met Chinese champignons', 12.2, 'VLEES GERECHTEN (met witte rijst)', null],
            [96, 79, null, 'Varkenshaas met zwarte bonensaus', 12.2, 'VLEES GERECHTEN (met witte rijst)', null],
            [97, 79, 'A', 'Varkenshaas met verse ananas in zoetzure saus', 13.3, 'VLEES GERECHTEN (met witte rijst)', null],
            [98, 79, 'B', 'Yu Sian Yuk', 13.3, 'VLEES GERECHTEN (met witte rijst)', 'varkenshaas met licht zoet pikante kruiden saus'],
            [99, 79, 'C', 'SzeChuan Yuk', 13.3, 'VLEES GERECHTEN (met witte rijst)', 'varkenshaas met pittige kruiden saus'],
            [100, 80, null, 'Ajam Pangang', 13, 'KIP GERECHTEN (met witte rijst)', null],
            [101, 81, null, 'Ajam Pangang in ketjapsaus', 13.2, 'KIP GERECHTEN (met witte rijst)', null],
            [102, 82, null, 'Ajam Pangang in pikante saus', 13.8, 'KIP GERECHTEN (met witte rijst)', null],
            [103, 83, null, 'Kipfilet met kerriesaus', 11.9, 'KIP GERECHTEN (met witte rijst)', null],
            [104, 84, null, 'Kipfilet met ketjapsaus', 11.9, 'KIP GERECHTEN (met witte rijst)', null],
            [105, 85, null, 'Kipfilet met tomatensaus', 11.9, 'KIP GERECHTEN (met witte rijst)', null],
            [106, 85, 'A', 'Kipfilet met champignons in knoflooksaus', 11.9, 'KIP GERECHTEN (met witte rijst)', null],
            [107, 85, 'B', 'Kipfilet met Chinese champignons', 12.2, 'KIP GERECHTEN (met witte rijst)', null],
            [108, 86, null, 'Kipfilet met zwarte bonensaus', 12.2, 'KIP GERECHTEN (met witte rijst)', null],
            [109, 86, 'A', 'Kipfilet met verse ananas in zoetzure saus', 13.3, 'KIP GERECHTEN (met witte rijst)', null],
            [110, 86, 'B', 'Yu Sian Kai', 13.3, 'KIP GERECHTEN (met witte rijst)', 'kipfilet met licht zoet pikante kruiden saus'],
            [111, 86, 'C', 'SzeChuan Kai', 13.3, 'KIP GERECHTEN (met witte rijst)', 'kipfilet met pittige kruiden saus'],
            [112, 87, null, 'Kipfilet met kerrie en groenten', 12.2, 'KIP GERECHTEN (met witte rijst)', null],
            [113, 88, null, 'Kipfilet met kerrie en cashewnoten', 13.3, 'KIP GERECHTEN (met witte rijst)', null],
            [114, 89, null, 'Tjap Tjoy met kipfilet en saté', 13.3, 'KIP GERECHTEN (met witte rijst)', null],
            [115, 90, null, 'Ajam Pangang met saté', 13.3, 'KIP GERECHTEN (met witte rijst)', null],
            [116, 91, null, 'Koe Loe Kai', 11.9, 'KIP GERECHTEN (met witte rijst)', 'kip met zoetzure saus'],
            [117, 97, null, 'Kung Bao Kai', 13.8, 'KIP GERECHTEN (met witte rijst)', 'kipfilet met cashewnoten in pittige saus'],
            [118, 98, null, 'Garnalen met champignons in knoflooksaus', 15.9, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [119, 99, null, 'Garnalen met tomatensaus', 15.9, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [120, 100, null, 'Garnalen met ketjapsaus', 15.9, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [121, 101, null, 'Garnalen met broccoli', 16.1, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [122, 102, null, 'Garnalen met Chinese champignons', 16.1, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [123, 103, null, 'Garnalen met kerriesaus', 16.1, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [124, 104, null, 'Garnalen met zwarte bonensaus', 16.1, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [125, 105, null, 'Garnalen met zwarte pepersaus', 16.1, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [126, 106, null, 'Garnalen met chilisaus', 16.1, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [127, 107, null, 'Yu Sian Haa', 16.1, 'GARNALEN GERECHTEN (met witte rijst)', 'garnalen met licht zoet pikante kruidensaus'],
            [128, 108, null, 'Tjieuw Yem Haa', 16.1, 'GARNALEN GERECHTEN (met witte rijst)', 'licht gebraden garnalen met zout en peper'],
            [129, 104, null, 'Ossenhaas met Chinese champignons', 16.4, 'OSSENHAAS GERECHTEN (met witte rijst)', null],
            [130, 105, null, 'Ossenhaas met kerriesaus', 15.3, 'OSSENHAAS GERECHTEN (met witte rijst)', null],
            [131, 106, null, 'Ossenhaas met ketjapsaus', 15.3, 'OSSENHAAS GERECHTEN (met witte rijst)', null],
            [132, 107, null, 'Ossenhaas met tomatensaus', 15.3, 'OSSENHAAS GERECHTEN (met witte rijst)', null],
            [133, 107, 'A', 'Ossenhaas met champignons in knoflooksaus', 15.3, 'OSSENHAAS GERECHTEN (met witte rijst)', null],
            [134, 107, 'B', 'Ossenhaas met zwarte bonensaus', 15.3, 'OSSENHAAS GERECHTEN (met witte rijst)', null],
            [135, 107, 'C', 'Ossenhaas met verse ananas in zoetzure saus', 16.4, 'OSSENHAAS GERECHTEN (met witte rijst)', null],
            [136, 107, 'D', 'Yu Sian Ngau', 16.4, 'OSSENHAAS GERECHTEN (met witte rijst)', 'ossenhaas met licht zoet pikante saus'],
            [137, 107, 'E', 'SzeChuan Ngau', 16.4, 'OSSENHAAS GERECHTEN (met witte rijst)', 'ossenhaas met pittige kruiden saus'],
            [138, 108, null, 'Kerrie garnalen met groenten', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [139, 109, null, 'Gebakken garnalen met groenten', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [140, 110, null, 'Garnalen met tomatensaus', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [141, 111, null, 'Garnalen met kerriesaus', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [142, 112, null, 'Garnalen met champignons in knoflooksaus', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [143, 113, null, 'Garnalen met zwarte bonensaus', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [144, 114, null, 'Garnalen met verse ananas in zoetzure saus', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', null],
            [145, 115, null, 'Yu Sian Har', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', 'garnalen met licht zoet pikante kruiden saus'],
            [146, 116, null, 'SzeChuan Har', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', 'garnalen met pittige kruiden saus'],
            [147, 117, null, 'Tau Sie Kai', 12.3, 'KIP GERECHTEN (met witte rijst)', 'kipfilet met zwarte bonensaus'],
            [148, 118, null, 'Tau Sie Yuk', 12.3, 'VLEES GERECHTEN (met witte rijst)', 'varkenshaas met zwarte bonensaus'],
            [149, 119, null, 'Tau Sie Ngau', 15.3, 'OSSENHAAS GERECHTEN (met witte rijst)', 'ossenhaas met zwarte bonensaus'],
            [150, 120, null, 'Tau Sie Har', 15.3, 'GARNALEN GERECHTEN (met witte rijst)', 'garnalen met zwarte bonensaus'],
            [151, null, 'T1', 'Tiepan Ling Fa', 17.9, 'TIEPAN SPECIALITEITEN (met witte rijst)', 'garnalen, kipfilet, ossenhaas en groenten in zwarte pepersaus'],
            [152, null, 'T2', 'Tiepan Kai', 15.3, 'TIEPAN SPECIALITEITEN (met witte rijst)', 'licht gebraden kipfilet en groenten met zoet pikante saus'],
            [153, null, 'T3', 'Tiepan San Yuk', 17.1, 'TIEPAN SPECIALITEITEN (met witte rijst)', 'lichtgrbaden varkenshaas, kipfilet, ossenhaas en groenten met zoet pikante saus'],
            [154, null, 'T4', 'Tiepan Haa', 17.4, 'TIEPAN SPECIALITEITEN (met witte rijst)', 'garnalen en groenten met zoet pikante saus'],
            [155, null, 'T5', 'Tiepan Ngau Yuk', 19.5, 'TIEPAN SPECIALITEITEN (met witte rijst)', '5st. ossenhaas en groenten met zoet pikante saus'],
            [156, null, 'V4', 'Tau Fu Po', 15.3, 'TIEPAN SPECIALITEITEN (met witte rijst)', 'sojakaas, cha sieuw garnalen en chinese paddenstoelen'],
            [157, null, 'V1', 'Vegetarische Tjap Tjoy', 8.3, 'VEGETARISCHE GERECHTEN (met witte rijst)', null],
            [158, null, 'V2', 'Lo Han Zhai', 11.2, 'VEGETARISCHE GERECHTEN (met witte rijst)', 'sojakaas, Chinese paddenstoelen en groenten in knoflooksaus'],
            [159, null, 'V3', 'Vegetarische Foe Yong Hai', 8.3, 'VEGETARISCHE GERECHTEN (met witte rijst)', null],
            [160, null, 'K1', 'Frites, saté (2st.) en ei', 6.5, 'KINDERMENUS', null],
            [161, null, 'K2', 'Frites, kippootje en ei', 6.5, 'KINDERMENUS', null],
            [162, null, 'K3', 'Frites, mini loempia (2st.) en ei', 6.5, 'KINDERMENUS', null],
            [163, null, 'K4', 'Kinder Bami of Nasi met saté (2st.) en ei', 6.5, 'KINDERMENUS', null],
            [164, null, 'R1', 'Indische rijsttafel (voor 1 persoon)', 16.4, 'RIJSTTAFELS', 'Gado gado, Foe Yong Hai, saté, Daging Roedjak, Daging Smoor, Ajam Ketjap, Atjar, Pisang Goreng, Pindas en Cocos'],
            [165, null, 'R2', 'Indische rijsttafel<br>Vanaf 2 personen... Per persoon', 15, 'RIJSTTAFELS', 'Ajam Ketjap, Gado Gado, Daging Smoor, Kroepoek, Daging Roedjak, Foe Yong Hai, Saté, Sambal Goreng Boontjes, Sambal Goreng Kering, Atjar, Pisang Goreng, Pinda en Cocos'],
            [167, null, 'R3', 'Chinese Indische Rijsttafel<br>Vanaf 4 personen... per persoon', 16.5, 'RIJSTTAFELS', 'Foe Yong Hai, Babi Pangang, Tjap Tjoy, Koe Loe Yuk, Ajam Ketjap, Daging Smoor, Daging Roedjak, Saté, Ei, Kroepoek, Sambal Goeren boontjes, Atjar, Pisang Goreng, Pinda en Cocos'],
            [168, null, 'R4', 'Chinese Rijsttafel<br>Vanaf 2 personen... per persoon', 17, 'RIJSTTAFELS', 'Kippen- of Tomatensoep, Tjap Tjoy met kipfilet, Koe Loe Yuk, Gebakken garnalen, Babi Pangang, Foe Yong Hai, saté, kroepoek'],
            [169, null, 'R5', 'Kantones Rijsttafel<br>Vanaf 2 personen... per persoon', 23, 'RIJSTTAFELS', 'Wan Tan soep, Chinese Dim Sum (mini loempia, kerrie ko, pangsit goreng, garnalen, pasteitje), Geroosterde Peking Eend, Lychee Kai (licht gebraden kipfilet met lychee in zoetzure saus), Tau Sie Haa (garnalen met zwarte bonensaus)'],
            [170, null, 'R6', 'Sze Chuan Rijsttafel<br>Vanaf 2 personen... per persoon', 23, 'RIJSTTAFELS', 'Peking Soep (pittige lichtzure soep), Chinese Dim Sum (mini loempia, kerrie ko, pangsit goreng, garnalen, pastei(tje)), Tjieuw Yem Kai (licht gebakken kipfilet met zout en peper), Lychee Yuk (licht gebraden varkensvlees met lychee in zoetzure saus), Yu Sian Ngau Yuk (ossenhaas met licht zoet pikante kruiden saus)'],
            [171, null, null, 'Buffet Menu A, per persoon', 12.8, 'BUFFET', 'Mini Loempia\'s, Pisang Goreng, Babi Pangang, Koe Loe Yuk, Foe Yong Hai, Kipfilet met zwarte bonensaus, Tjap Tjoy met kipfilet, saté Ajam'],
            [172, null, null, 'Buffet Menu B, per persoon', 15, 'BUFFET', 'Mini Loempia\'s, Pisang Goreng, Babi Pangang, Foe Yong Hai, Kung Bao Kai, Hong Shau Yu, saté Ajam, Ossenhaas met zwarte bonensaus, Kipfilet met kerriesaus'],
            [173, null, null, 'Bami of Nasi Goreng ipv rijst', 0.9, 'DIVERSEN', null],
            [174, null, null, 'Mihoen Goreng ipv rijst', 2.5, 'DIVERSEN', null],
            [175, null, null, 'Chinese Bami ipv rijst', 2.5, 'DIVERSEN', null]
        ];

        foreach ($items as [$id, $menuNumber, $menuSuffix, $name, $price, $type, $description]) {
            $dishTypeId = DB::table('dish_types')->where('name', $type)->value('id');

            DB::table('menu_items')->insert([
                'id' => $id,
                'menu_number' => $menuNumber,
                'menu_suffix' => $menuSuffix,
                'name' => $name,
                'price' => $price,
                'dish_type_id' => $dishTypeId,
                'description' => $description,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
